name: SubServer
version: '${project.version}'
main: com.stackmc.subserver.SubServer
api-version: '1.20.6'
authors: [LoanSpac, Clooooud, Bloupyi]
load: POSTWORLD
commands:
  subserver:
    description: "SubServer's main command"